// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIAMW1vw-xD8r3u0Rujfm0QdAsA7FmeY',
    appId: '1:908446627310:ios:e95cb3c1c3be9b7dd70aff',
    messagingSenderId: '908446627310',
    projectId: 'progress-pals-7cabd',
    storageBucket: 'progress-pals-7cabd.firebasestorage.app',
    iosClientId: '908446627310-e9gkd2ciprftonfjv2d286017mon8o53.apps.googleusercontent.com',
    iosBundleId: 'com.lesetja.progressPals',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD829kNJhA5bwLCXtvZ_6Pv0OTFB0nx3Cs',
    appId: '1:908446627310:android:d96d22320f20b945d70aff',
    messagingSenderId: '908446627310',
    projectId: 'progress-pals-7cabd',
    storageBucket: 'progress-pals-7cabd.firebasestorage.app',
  );

}